{% set version = "2.4.3" %}

package:
  name: proxy-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/proxy.py/proxy.py-{{ version }}.tar.gz
  sha256: 6134e8f1282db1fd7fa1a4b7049e49307566851023b2ac312d9dd36e92f0c9b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - proxy = proxy:entry_point
  script_env:
    - PYTHONIOENCODING=utf-8
    - PYTHONLEGACYTEXTENCODING=utf-8

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm >=6,!=7.0.0,!=7.0.1,!=7.0.2
  run:
    - python >=3.6

test:
  imports:
    - proxy
  commands:
    - pip check
    - proxy --help
  requires:
    - pip

about:
  home: https://github.com/abhinavsingh/proxy.py
  summary: Proxy Server, Web Server, PubSub, Work acceptor & executor framework.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
