{% set version = "2.4.9" %}

package:
  name: proxy-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/proxy.py/proxy_py-{{ version }}.tar.gz
  sha256: 98676034f94615097bcbe383de65e20a7a2bed74431ffdfd073ece76f3d6e366

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - proxy = proxy:entry_point
    - grout = proxy:grout
  script_env:
    - PYTHONIOENCODING=utf-8
    - PYTHONLEGACYTEXTENCODING=utf-8

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=7.0.5
  run:
    - python >={{ python_min }}

test:
  imports:
    - proxy
  commands:
    - pip check
    - proxy --help
    - which grout || where grout
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/abhinavsingh/proxy.py
  summary: Proxy Server, Web Server, PubSub, Work acceptor & executor framework.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://proxypy.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
