{% set version = "2.4.4" %}

package:
  name: proxy-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/proxy.py/proxy_py-{{ version }}.tar.gz
  sha256: 216581f70ad673f4ecb5f6b27f52491aaf1c056829f4a670f5ea3b5a340f4272

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - proxy = proxy:entry_point
  script_env:
    - PYTHONIOENCODING=utf-8
    - PYTHONLEGACYTEXTENCODING=utf-8

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm >=7.0.5
  run:
    - python >=3.6

test:
  imports:
    - proxy
  commands:
    - pip check
    - proxy --help
  requires:
    - pip

about:
  home: https://github.com/abhinavsingh/proxy.py
  summary: Proxy Server, Web Server, PubSub, Work acceptor & executor framework.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://proxypy.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
